### ISSUE TITLE
Recipients "Show details" button disappears

### ISSUE THREAD

**Issue by ballII** [igorsantos07/Gmail-Inline-Image-Fit#7]
The recipients "Show details" drop-down button shrinks to a point after installing Inline Image Fit, making it very difficult to aim and click the button.

![Screen Shot 2019-05-27 at 9 07 46 PM](https://user-images.githubusercontent.com/7100993/58421800-8895af80-80c3-11e9-8076-8f7d8d37ac4d.png)

**Comment by mrechter** [comment]
I am also seeing this issue

**Comment by aboushley** [comment]
I am also seeing this issue.

**Comment by SamBeckett97** [comment]
Was this issue fixed but never committed?  I'm still experiencing this problem and would love to get an updated extension.

**Comment by SamBeckett97** [comment]
Thank you for fixing!!!
