### ISSUE TITLE
Senders Profile Picture Enlarged

### ISSUE THREAD

**Issue by aboushley** [igorsantos07/Gmail-Inline-Image-Fit#8]
I have noticed that this extension causes the senders profile picture at the top left of emails to be enlarged.

Is this a bug or a feature?

If it is a bug, please see if there is a way to fix it.

If it is a feature, can this be made an optional feature so that it can be switched off?

Thanks!

**Comment by richardxia** [comment]
I noticed this issue as well and made a fix in https://github.com/igorsantos07/Gmail-Inline-Image-Fit/pull/10.
